#!/bin/bash

# Build the image
docker build -t apm-publication-api-php84 -f docker/php84/Dockerfile .

# Run the container
# No volume mount needed as files are copied into the image for isolation
docker run --rm apm-publication-api-php84
